# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Ch2L2
                                 A QGIS plugin
 This plugin generates reflectance from Radiance data of  Imaging Infrared Radio Specrometer sensor of Chandrayaan 2
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-04-24
        copyright            : (C) 2023 by Prabhakar Alok Verma, Mamta Chauhan, Prakash Chauhan
        email                : prabhakar.9219@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Ch2L2 class from file Ch2L2.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .Thermal import Ch2L2
    return Ch2L2(iface)
